name: gsdb
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=25.0.1
  - python=3.13.2
  - pytorch=2.6.0
  - torchvision=0.21.0
  - cudatoolkit=11.7
  - pillow=11.1.0
  - libjpeg-turbo
  - libpng
  - opencv
  - optuna=4.2.1
  - tqdm=4.67.1
  - colorlog=6.9.0
  - numpy=2.2.3
  - matplotlib
  - pandas=2.2.3
  - scikit-learn
  - scikit-image
  - seaborn
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - autograd==1.7.0
      - autograd-gamma==0.5.0
      - braceexpand==0.1.7
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - fairscale==0.4.13
      - fonttools==4.56.0
      - formulaic==1.1.1
      - fsspec==2025.2.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.70.0
      - h5py==3.13.0
      - huggingface-hub==0.29.1
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - interface-meta==1.3.0
      - iopath==0.1.10
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lifelines==0.30.0
      - markdown==3.7
      - matplotlib==3.9.4
      - monai==1.4.0
      - mypy-extensions==1.0.0
      - ninja==1.11.1.1
      - numexpr==2.10.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openslide-bin==4.0.0.6
      - openslide-python==1.4.1
      - osqp==0.6.7.post3
      - packaging==23.2
      - pandas==2.2.3
      - shapely==2.0.7
      - platformdirs==4.3.6
      - portalocker==3.1.1
      - protobuf==5.29.3
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pyre-extensions==0.0.23
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - qdldl==0.1.7.post5
      - regex==2024.11.6
      - safetensors==0.5.2
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scikit-survival==0.23.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timm==1.0.15
      - tokenizers==0.15.2
      - torchmetrics==0.10.3
      - transformers==4.49.0
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - wandb==0.19.7
      - webdataset==0.2.100
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yacs==0.1.8
