name: gsdb
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - huggingface_hub
  - conda-forge::timm
  - pip:
      - scikit-learn
      - torch
      - shapely
      - openslide-bin