name: gsdb
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - huggingface_hub
  - timm
  - pytorch
  - torchvision
  - torchaudio
  - nvidia::pytorch-cuda=11.8
  - scikit-learn
  - shapely
  - openslide
  - optuna
  - pyyaml
  - plotly
  - scikit-image
  - tqdm
  - pip:
      - openslide-bin
      - pycocotools
      - torchmetrics
      - albumentations
      - tk
      - opencv-python
