name: gsdb
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip=25.0.1
  - python=3.13.2
  - pytorch=2.6.0
  - torchvision=0.21.0
  - pytorch-cuda=12.4
  - conda-forge::huggingface_hub
  - conda-forge::timm
  - pillow=11.1.0
  - libjpeg-turbo
  - libpng
  - opencv
  - optuna=4.2.1
  - tqdm=4.67.1
  - colorlog=6.9.0
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - seaborn
  - pip:
      - wandb
      - transformers
      - tensorboard
      - scipy
      - einops
      - h5py
      - openslide-python
      - scikit-survival